baseURL = "https://packetpwned.com"
locale = "en-us"
title = "PacketPwned"

[params]
  author = "Majid Ahmed"
  description = "Designing secure & resilient networks. CCIE #55880 | CISSP | Pentester."
  tagline = "Designing Secure & Resilient Networks"
  linkedin = "https://linkedin.com/in/majid-ahmed-b6006640/"

[menu]
  [[menu.main]]
    name = "Writeups"
    url = "/writeups/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

[taxonomies]
  tag = "tags"
  category = "categories"
